export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const LOGOUT = "LOGOUT";

export const SERVER_FETCH_STARTED = "SERVER_FETCH_STARTED";
export const SERVER_FETCH_SUCCESS = "SERVER_FETCH_SUCCESS";
export const SERVERS_FETCH_STARTED = "SERVERS_FETCH_STARTED";
export const SERVERS_FETCH_SUCCESS = "SERVERS_FETCH_SUCCESS";
export const USER_SERVERS_FETCH_STARTED = "USER_SERVERS_FETCH_STARTED";
export const USER_SERVERS_FETCH_SUCCESS = "USER_SERVERS_FETCH_SUCCESS";
export const JOIN_SERVER_STARTED = "JOIN_SERVER_STARTED";
export const JOIN_SERVER_SUCCESS = "JOIN_SERVER_SUCCESS";
export const FETCH_FAIL = "FETCH_FAIL";
export const JOIN_FAIL = "JOIN_FAIL";
export const CREATE_CATEGORY_SUCCESSFUL = "CREATE_CATEGORY_SUCCESSFUL";
export const CREATE_CHANNEL_FAIL = "CREATE_CATEGORY_FAIL";
export const CREATE_CHANNEL_SUCCESSFUL = "CREATE_CATEGORY_SUCCESSFUL";
export const CREATE_CATEGORY_FAIL = "CREATE_CATEGORY_FAIL";

export const SERVER_CREATED = "SERVER_CREATED";
export const SERVER_CREATION_FAILED = "SERVER_CREATION_FAILED";
